### ISSUE TITLE
Add more markdown rendering themes

### ISSUE THREAD

**Issue by zedxxx** [EtheaDev/MarkdownHelpViewer#3]
It would be great if there were more built-in themes. I would especially like to see a theme similar to the one that uses GitHub.

Better yet, the user can add their own themes.

**Comment by carloBarazzetta** [comment]
If you have Delphi 11, you can rebuild the viewer adding any VCL Theme that you want...
if you need to rendering the html output, you can add a .css file in the working dir (for example home.css as you can see in the demo) so the viewer can render the HTML output as you want.

**Comment by carloBarazzetta** [comment]
Closed issue: no feedback received.
