### ISSUE TITLE
MDHelpViewer.exe Ver. 2.0.1 can not open .html file

### ISSUE THREAD

**Issue by dxu135** [EtheaDev/MarkdownHelpViewer#5]
MDHelpViewer.exe Ver. 2.0.1 can not open .html file

**Comment by carloBarazzetta** [comment]
Can you give me more details? I can Open html file without problem from the GUI: "Open", select "html text file" from the combobox right/botton and i can see it into the viewer:
![image](https://github.com/EtheaDev/MarkdownHelpViewer/assets/7803548/8e2073e3-9473-4f80-be93-69c7bf8fe6d6)

**Comment by dxu135** [comment]
Hi,
here is the file [https://res-h3.public.cdn.office.net/assets/mail/file-icon/png/code_16x16.png] index.html<https://1drv.ms/u/s!Aq7dH37jX-Ev6EplDMdDee5eFtdL>, which I can't open

Mit freundlichen Grüßen,
Danyang Xu
***@***.***>
________________________________
Von: Carlo Barazzetta ***@***.***>
Gesendet: Dienstag, 31. Oktober 2023 09:05
An: EtheaDev/MarkdownHelpViewer ***@***.***>
Cc: dxu135 ***@***.***>; Author ***@***.***>
Betreff: Re: [EtheaDev/MarkdownHelpViewer] MDHelpViewer.exe Ver. 2.0.1 can not open .html file (Issue #5)


Can you give me more details? I can Open html file without problem from the GUI: "Open", select "html text file" from the combobox right/botton and i can see it into the viewer:
[image]<https://user-images.githubusercontent.com/7803548/279300760-8e2073e3-9473-4f80-be93-69c7bf8fe6d6.png>

**Comment by carloBarazzetta** [comment]
This html file is not static, containts some javascript code and is not an "output" of a markdown file. HTMLViewer is capable to view markdown files, or static HTML produced by a transformation of markdown to HTML.
