### ISSUE TITLE
Minor table issue

### ISSUE THREAD

**Issue by BazzaCuda** [EtheaDev/MarkdownHelpViewer#6]
Hi. Great project! I'm looking forward to incorporating TMarkdownViewer in my application.

In my readme.md I have a table defined, like this:
### Full List of Controls By Category
---------------
Control | Action
------- | ------
**Brightness** | 
`8`                     | decrease brightness. Can be held down for rapid decrease
`9`                     | increase brightness. Can be held down for rapid increase
`2`                     | reset brightness to normal

It displays correctly on Github. As you can see, my first column doubles as a section header throughout the long table. However, TMarkdownViewer has a problem when my second column doesn't have a value in it. Everything following the vertical bar after "Brightness" is taken as the contents of the second column. (the md is `**Brightness** |` )

If I add a dot or any character at all after the Brightness vertical bar it works. However, if I do that on Github it spoils the look of my table.
As you can see here, I added a random _ in column 2 and TMarkdownViewer works well until the next section header ("Contrast"):
![image](https://github.com/EtheaDev/MarkdownHelpViewer/assets/22550919/27969de4-5498-41b1-bbc3-3cfe80d9d924)

It would be great if this could be fixed as I can then use my github readme.md in TMarkdownViewer without alteration.

Thanks.

**Comment by BazzaCuda** [comment]
I have found a work-around, which is to have two vertical bars after Brightness. This works both on Github and in TMarkdownViewer.

**Comment by carloBarazzetta** [comment]
Good news, because the "rendering" is made by the [EtheaDev/MarkdownProcessor](https://github.com/EtheaDev/MarkdownProcessor) that is not mine. 

I've only made a porting of a Freepascal version of the original processor to Delphi, as explained in the project, so I cannot help you to resolve your particular issue...

**Comment by BazzaCuda** [comment]
Ah, ok, no problem. Thanks for your reply.
