### ISSUE TITLE
Installing the components

### ISSUE THREAD

**Issue by mib42** [EtheaDev/MarkdownHelpViewer#7]
Hi all
I tried to install the MarkDownHelpViewer component like described in the Wiki but an error appears:
  FrameViewer10_2;   is required but could not be found.
Can you give me a hint please, what my mistake is?
Thanks a lot
Michael

**Comment by carloBarazzetta** [comment]
Wich Delphi version are you using?

**Comment by mib42** [comment]
Sorry, I forgot
Delphi 10.2 Enterprise

**Comment by carloBarazzetta** [comment]
Did you have installed HTMLViewer in your IDE? I've notice a difference on package names and I'll fix it in the next version as soon as possible...

**Comment by carloBarazzetta** [comment]
Fixed in 2.3.2 version: please read the updated [installation steps here](https://github.com/EtheaDev/MarkdownHelpViewer/wiki/How-to-Install-the-Components)

**Comment by mib42** [comment]
Thank you very much for yout help. It works now.
